"""inicial migration

Revision ID: 368cc43c0405
Revises: 
Create Date: 2026-01-22 16:33:44.892929

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368cc43c0405'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_types_deleted_at'), 'experiment_types', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_experiment_types_name'), 'experiment_types', ['name'], unique=True)
    op.create_table('model_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'available'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_types_deleted_at'), 'model_types', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_model_types_name'), 'model_types', ['name'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('external_experiment_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('experiment_type_id', sa.Integer(), nullable=True),
    sa.Column('model_type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_type_id'], ['experiment_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_type_id'], ['model_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_deleted_at'), 'experiments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_experiments_experiment_type_id'), 'experiments', ['experiment_type_id'], unique=False)
    op.create_index(op.f('ix_experiments_external_experiment_id'), 'experiments', ['external_experiment_id'], unique=True)
    op.create_index(op.f('ix_experiments_model_type_id'), 'experiments', ['model_type_id'], unique=False)
    op.create_index(op.f('ix_experiments_name'), 'experiments', ['name'], unique=False)
    op.create_index(op.f('ix_experiments_project_id'), 'experiments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiments_project_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_model_type_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_external_experiment_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_experiment_type_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_deleted_at'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_model_types_name'), table_name='model_types')
    op.drop_index(op.f('ix_model_types_deleted_at'), table_name='model_types')
    op.drop_table('model_types')
    op.drop_index(op.f('ix_experiment_types_name'), table_name='experiment_types')
    op.drop_index(op.f('ix_experiment_types_deleted_at'), table_name='experiment_types')
    op.drop_table('experiment_types')
    # ### end Alembic commands ###
