"""detect changes

Revision ID: 745db99c7486
Revises: b2c8d4e5f6a7
Create Date: 2026-01-23 12:00:34.614885

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745db99c7486'
down_revision: str | None = 'b2c8d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataset_file_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_experiments_dataset_file_id'), ['dataset_file_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_experiments_dataset_file_id', 'dataset_files', ['dataset_file_id'], ['id'], ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_experiments_dataset_file_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_experiments_dataset_file_id'))
        batch_op.drop_column('dataset_file_id')
    # ### end Alembic commands ###
